charts/neon-proxy/Chart.yaml, charts/neon-proxy/README.md, charts/neon-proxy/templates/deployment.yaml, charts/neon-proxy/values.yaml, charts/neon-storage-broker/Chart.yaml, charts/neon-storage-broker/README.md, charts/neon-storage-broker/templates/deployment.yaml, charts/neon-storage-broker/values.yaml
Neon-proxy and neon-broker-storage charts were affected.
=> Bypass SENTRY_ENVIRONMENT variable in order to send relevant value to Sentry.

charts/neon-proxy/Chart.yaml, charts/neon-proxy/README.md, charts/neon-proxy/templates/deployment.yaml, charts/neon-proxy/values.yaml
In order to achieve zero downtime deployments, the deployment strategy needs to be customizable from `Recreate`, which pretty much ensures downtime.
`terminationGracePeriodSeconds` dictates for how long can the pods wait for being forcefully terminated, so it's essential to make that customizable too. The default is being set to kubernetes default.
Finally, since we might have different signal than the default for graceful shutdown, need to be able to customize the neon-proxy container's `lifecycle` to have that as `preStop` command.
=> Support deployment strategy and grace time customization

charts/neon-proxy/Chart.yaml, charts/neon-proxy/README.md, charts/neon-proxy/templates/_helpers.tpl, charts/neon-proxy/templates/certificate.yaml, charts/neon-proxy/templates/certificates-extra.yaml, charts/neon-proxy/templates/deployment.yaml, charts/neon-proxy/values.yaml
- Creates TLS cert for each domain listed in extraDomains
- Mount them under subfolders of `/certs-extra`
- Passes that folder as `--certs-dir` to proxy
https://github.com/neondatabase/cloud/issues/4397
=> Add support for extra certs for SCRAM proxy

charts/neon-storage-broker/Chart.yaml, charts/neon-storage-broker/README.md, charts/neon-storage-broker/templates/deployment.yaml
We had an issue with broker ~2 minutes downtime on redeploy (https://github.com/neondatabase/cloud/issues/5234). The cause of this issue is AWS Load Balancer, which takes 2 minutes to pass health checks for the new target.
This [page](https://aws.github.io/aws-eks-best-practices/networking/loadbalancing/loadbalancing/#utilize-pod-readiness-gates) suggests a fix for the problem:
1. Use RollingUpdate strategy for the service
2. Enable Readiness Gate for the LoadBalancer
This PR does the (1), and I also tested the fix by doing (2) manually:
```
kubectl label namespace neon-storage-broker-lb elbv2.k8s.aws/pod-readiness-gate-inject=enabled
```
AFAIK, there is no way to add namespace labels from a helm chart, so I will also create a PR in aws repository.
=> Use RollingUpdate for storage-broker

charts/neon-pg-sni-router/Chart.yaml, charts/neon-pg-sni-router/README.md, charts/neon-pg-sni-router/values.yaml
It was `Recreate` by default, which were causing a downtime each release.
I see that `proxy` also has `Recreate` by default and `RollingUpdate` is specified in the `aws` repo. Yet, for proxy it probably makes sense as link-auth and SCRAM proxies use different strategies and the same helm chart now. SNI router is completely stateless and using `RollingUpdate` by default is reasonable.
Related to neondatabase/cloud#5265
=> Use RollingUpdate strategy for SNI router

.github/workflows/lint-test.yaml, charts/aws-cost-reporter/Chart.yaml, charts/aws-cost-reporter/README.md, charts/aws-cost-reporter/templates/cronjob.yaml, ct.yaml
- Move from k3d to kind for chart testing
- Minor fix in was-cost-reporter
=> Update in github actions

charts/neon-proxy/Chart.yaml, charts/neon-proxy/README.md, charts/neon-proxy/templates/deployment.yaml, charts/neon-proxy/values.yaml
Reverts neondatabase/helm-charts#55
This should be fine to add back in now :D
=> Revert "Revert "proxy-parquet-config""

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/templates/deployment.yaml, charts/neon-storage-controller/values.yaml
Intentionally not bumping the version because this can stay at 1.0.0 util it is stabilized enough to go into prod use.
- Fix jwtToken variable handling
- Add controlPlaneJwtToken, computeHookUrl
- Use recently added `/ready` endpoint as readiness check.
=> neon-storage-controller: add params for compute hook, readiness hook

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/scripts/register-storage-controller.py
Cplane only accept `node_id` as integer and script were sending string. 
```
neon-control-plane-api-0 neon-control-plane {"level":"ERR","ts":"2024-03-04T12:51:53.388Z","logger":"managementapiv2","message":"incoming request finished with error","http_meth":"POST","http_path":"/management/api/v2/pageservers","route":"PageserverRegister","request_id":"8c1da1d9ae780811e3debd558cc261b6","trace_id":"2qCK96h5WSEyyNMa4CB9Qc","ingress_duration_ms":0,"status":400,"error":"invalid request: decode application/json: decode PageserverRegisterRequest: callback: decode field \"node_id\": unexpected byte 34 '\"' at 495: operation PageserverRegister: decode request: decode application/json: decode PageserverRegisterRequest: callback: decode field \"node_id\": unexpected byte 34 '\"' at …
```
=> fix: storage controller registration script

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/templates/deployment.yaml
This is an update to reflect the changed name in https://github.com/neondatabase/neon/pull/7042
Additionally update the readiness check settings to reflect that I have been using in deploys to eu-west-1, and set RUST_BACKTRACE (this is useful in case of panics)
=> storage controller: update binary name

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/templates/deployment.yaml
Helm deployment failed with following error:
```
Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal number into Go struct field EnvVar.spec.template.spec.containers.env.value of type string
```
Ref: https://github.com/neondatabase/aws/actions/runs/8202890489/job/22434609060
=> double quotes value in deployment envs

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/templates/deployment.yaml
Helm (or Go formatting more generally) apparently arbitrarily uses scientific notation for integers above a million when quoting.
Try passing it through without the `| quote` to see if a simple integer makes it through unscathed.
=> storage controller: don't `| quote` split threshold

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/templates/deployment.yaml
Crazy times with YAML & Go...
In https://github.com/neondatabase/helm-charts/pull/83 I got rid of the `| quote` because that was a possible cause of an integer getting wrongly formatted.
However, even after https://github.com/neondatabase/aws/pull/1358 changes the input type of splitThreshold to a string, the substitution into kubernetes YAML implicitly turns it back into an integer, and kubernetes requires that all the elements in the `commands` array be strings (not just things that can be string-ized).
TLDR: to make the splitThreshold work, we just need to add the `| quote` back.  This was tested in https://github.com/neondatabase/aws/pull/1361 by deploying with the earlier version of the helm chart.
=> Revert "Don't quote splitThreshold" 

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/scripts/register-storage-controller.py
Currently I'm trying to setup a storage controller in a new environment but registration is failing
with a `Unable to find pageserver version from` message, which doesn't tell much. I'm sure there's a
configuration error somewhere but it's hard to debug when the message doesn't contain any details.
This PR changes the `get_data` method to raise an exception on unexpected responses so that the
status code and response body are shown. Also changes the same method to not silently discard
`urllib.error.URLError` if it happens.
This doesn't change the behavior of the registration script significantly because we're already
exiting if the response doesn't contain what we need.
=> show errors received on registration

charts/neon-proxy/Chart.yaml, charts/neon-proxy/README.md, charts/neon-proxy/templates/deployment.yaml, charts/neon-proxy/values.yaml
This adds additional parameter, `--redis-auth-type` to proxy startup CLI arguments. The default is "irsa", and it should be a backward compatible default.
https://github.com/neondatabase/cloud/issues/14462
=> [proxy/cplane-communication] refactor: support switching auth type

charts/neon-storage-scrubber/Chart.yaml, charts/neon-storage-scrubber/README.md, charts/neon-storage-scrubber/templates/cronjob.yaml, charts/neon-storage-scrubber/templates/secrets.yaml, charts/neon-storage-scrubber/values.yaml
This pull request adds 3 fields to the helm chart to support scrubber<->controller auth.
```
enableStorageControllerConnection: false
storageControllerJwtToken: ""
storageControllerUrl: ""
```
Also, users no longer need to supply the executable path in the command field.
Tested by deploying this chart to dev-us-east-2 and it works.
=> storage-scrubber: enable jwt auth with storage controller

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/templates/deployment.yaml
The storage controller needs to know the address at which it is reachable by it's peers within the deployment. It will use this to mark itself as the leader in the database.
The CLI arg was added in https://github.com/neondatabase/neon/pull/8588 and that's already been deployed everywhere.
Note that we are not enabling graceful leadership tranfers with this change. The only change in storcon behaviour is that each instance will write its address into the database at start-up. If that fails, the process exits.
=> Inject address for peers at storage controller start-up

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/templates/deployment.yaml, charts/neon-storage-controller/values.yaml
Add a `startAsCandidate` setting for the storcon helm chart (default `false`).
When set to true, the service restarts gracefully (see https://github.com/neondatabase/neon/pull/8310).
This doesn't change anything as is. Changes to `neondatabase/infra` will stage the roll-out of this.
=> Add helm chart option for graceful service restart

charts/neon-proxy/Chart.yaml, charts/neon-proxy/README.md, charts/neon-proxy/templates/service.exposed.yaml, charts/neon-proxy/values.yaml
Across providers there might be a need to change externalTrafficPolicy for the external Service. Keep the default as Cluster, which is the default in Kubernetes.
=> Add support foir changing proxy Service's externalTrafficPolicy

charts/neon-proxy/Chart.yaml, charts/neon-proxy/README.md, charts/neon-proxy/templates/deployment.yaml, charts/neon-proxy/values.yaml
- Add support for additional command line arguments
- This will be use to deploy proxy in private access mode i.e. `--is-private-access-proxy` flag
Ref: https://github.com/neondatabase/neon/issues/9033
=> proxy: Add support for additional command line arguments

charts/neon-proxy/Chart.yaml, charts/neon-proxy/README.md, charts/neon-proxy/templates/deployment.yaml, charts/neon-proxy/values.yaml
resolves https://github.com/neondatabase/cloud/issues/18026
depends on https://github.com/neondatabase/neon/pull/9203
=> add proxy-protocol-v2 flag to proxy charts

charts/neon-storage-scrubber/Chart.yaml, charts/neon-storage-scrubber/README.md, charts/neon-storage-scrubber/templates/cronjob.yaml, charts/neon-storage-scrubber/values.yaml
Adds an object-typed `remoteStorageConfig` variable to `neon-storage-scrubber`.
Earlier PR: #88 
Part of https://github.com/neondatabase/cloud/issues/19963
=> Add remoteStorageConfig variable to neon-storage-scrubber

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/values.yaml
We could configure this in the values.yaml used when deploying, but it seems like a sensible default: we know that the controller can require more CPU when doing scheduling across large numbers of tenants, and have seen suspicious container terminations that might result from CPU starvation.
=> storcon: change default CPU request 200m->1

charts/neon-storage-scrubber/Chart.yaml, charts/neon-storage-scrubber/README.md, charts/neon-storage-scrubber/templates/cronjob.yaml
Looking at `secrets.yaml`, the env var is `STORAGE_CONTROLLER_JWT_TOKEN` and not `STORAGE_CONTROLLER_JWT`.
The token reaches the pod and is correct, but the invocation is wrong.
=> storage-scrubber: fix up secret env var name in cmdline

charts/neon-storage-scrubber/Chart.yaml, charts/neon-storage-scrubber/README.md, charts/neon-storage-scrubber/templates/cronjob.yaml, charts/neon-storage-scrubber/values.yaml
Required for setting labels on pods without modifying other labels.
=> storage-scrubber: add ability to set pod labels

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/templates/_helpers.tpl, charts/neon-storage-controller/templates/ingress.yaml, charts/neon-storage-controller/templates/service.yaml, charts/neon-storage-controller/values.yaml
We will migrate the storage controller from NLB to the ingress controller. 
Our plan for testing on staging:
- PR-1: Add ingress support to Helm chart  (This PR)
- PR-2: Deploy changes to staging (new values):
- Renaming DNS to `storage-controller-<dns>` --> `storage-controller-old-<dns>`   
- New Service which points to storage controller pod (this is required for nginx ingress controller)
- New Ingress rule with DNS `storage-controller-<dns>`
- Assuming the above changes are applied
- Clients will resolve to Ingress controller after TTL expires
- PR-3: Once everything works then, we can deprecate the old service NLB object i.e. `storage-controller-old-<dns>` by setting the value `serviceNLB: false`
Slack: https://neondb.slack.com/archives/C039YKBRZB4/p1734029656095099?thread_ts=173400148 …
=> chore(storcon): Set enable flag on NLB based service

README.md
We occasionally encounter folks who are disappointed that these helm charts don't deliver a full working Neon deployment -- they are just for a few components, so let's be up-front about that in the readme.
=> Note the limited scope of charts in the README.md

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/templates/deployment.yaml
This was set to use the Neon-built postgres to avoid needing an extra vanilla postgres client binary in the container image.
However, using that build was problematic when it switched to using statically compiled openssl (which is unsafe when used from multi-threaded binaries), so let's use
the system libpq instead.
Depends on https://github.com/neondatabase/neon/pull/10269 to provide the system docker package.
=> storage controller: do not set LD_LIBRARY_PATH

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/scripts/register-storage-controller.py
There isn't a good reason for why storage controller should be registered with an active state of
false. Registering them with `active=true` saves a manual action later.
https://neondb.slack.com/archives/C033RQ5SPDH/p1738770565943569
=> storage-controller registration: start with active=true

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/scripts/register-storage-controller.py, charts/neon-storage-controller/templates/post-install-job.yaml, charts/neon-storage-controller/values.yaml
We don't need to know the console URL or API keys since
https://github.com/neondatabase/helm-charts/pull/113, however, there's still some cleanup left.
The `CONSOLE_URL` variable is not used in `register-storage-controller.py` (except for logging), so
we can delete it and don't need to set it in the registration job either.
Similarly, API keys are not needed, remove references in values files and documentation.
Bump to version to 1.5.1, as this should be consired a bugfix to perform some belated cleanup.
=> storage-controller: remove unused vars, cleanup documentation

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/templates/deployment.yaml, charts/neon-storage-controller/values.yaml
As part of https://github.com/neondatabase/neon/pull/10934, we would like to exercise a force exit of storage controller (probably every day). This patch adds helm-charts support for it.
=> storcon: add chaos exit crontab

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/templates/secrets.yaml, charts/neon-storage-controller/values.yaml
Adds a safekeeper specific JWT token config variable to the helm chart of the storage controller.
Neon PR: https://github.com/neondatabase/neon/pull/10905
Part of https://github.com/neondatabase/cloud/issues/24727
=> Add safekeeper JWT token to storcon helm chart

.github/workflows/lint-test.yaml
v1.25 is no longer available, causing CI failures.
=> lint: bump k3s

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/templates/deployment.yaml, charts/neon-storage-controller/values.yaml
This patch adds support for the new split settings from https://github.com/neondatabase/neon/pull/11122:
* `initial_split_threshold`
* `initial_split_shards`
* `max_split_shards`
=> neon-storage-controller: add new split settings

charts/neon-proxy/Chart.yaml, charts/neon-proxy/README.md, charts/neon-proxy/templates/deployment.yaml, charts/neon-proxy/templates/root_ca.yaml, charts/neon-proxy/values.yaml
Proxy requires the root certificate of our internal CA in order to connect to computes via TLS.
=> add settings for root ca configmap for proxy

charts/neon-proxy/Chart.yaml, charts/neon-proxy/README.md, charts/neon-proxy/templates/root_ca.yaml
We need to output the root certificate as a block and indent accordingly in order to avoid YAML
parsing errors.
=> neon-proxy: output root certificate as block and indent

charts/neon-proxy/Chart.yaml, charts/neon-proxy/README.md, charts/neon-proxy/templates/deployment.yaml
Since proxy settings are delivered with ENV variables, the binary must restart when the `.Values.settings` change.
=> impr: proxy restarts when config changes

charts/neon-proxy/Chart.yaml, charts/neon-proxy/README.md, charts/neon-proxy/templates/deployment.yaml
Fix the proxy chart for instances that don't start the SNI router by conditionally mounting the relevant certificate.
=> proxy: Don't try to mount the SNI router cert when not configured

charts/neon-storage-broker/Chart.yaml, charts/neon-storage-broker/README.md, charts/neon-storage-broker/values.yaml
We've seen the broker OOM in prod because QoS for it is [best effort](https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/#besteffort).
Let's set explicit limits to deter that.
Note that in order to get this out we need to restart the service. Doing it live is [a v1.33 feature](https://kubernetes.io/docs/tasks/configure-pod-container/resize-container-resources/). Restarting broker is disruptive, so let's figure that out separately.
Some more context: https://neondb.slack.com/archives/C033RQ5SPDH/p1747932577771809?thread_ts=1747927318.201659&cid=C033RQ5SPDH
=> Use explicit resource request for broker service

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/templates/deployment.yaml, charts/neon-storage-controller/values.yaml
We'd like to reduce this for faster Pageserver failover times.
Adds `maxOfflineInterval`, `heartbeatInterval` and `maxWarmingUpInterval`, since we'll likely need to tune all three.
Touches https://github.com/neondatabase/cloud/issues/28852.
Touches https://github.com/neondatabase/neon/pull/12258.
=> storcon: add `maxOfflineInterval`, `heartbeatInterval`, and `maxWarmingUpInterval`
