charts/neon-proxy/Chart.yaml, charts/neon-proxy/README.md, charts/neon-proxy/templates/deployment.yaml
The deployment template had plurals for metricCollection -settings. The actual argument is singular and values.yaml have singular -> fix the template.
=> Fix the plurals metricsCollection... in the helm deployment template

CONTRIBUTING.md
fixed the guide based on my first contribution experience
=> Mention helm-docs in CONTRIBUTING.md

charts/neon-proxy/Chart.yaml, charts/neon-proxy/README.md, charts/neon-proxy/templates/deployment.yaml, charts/neon-proxy/values.yaml
See https://github.com/neondatabase/neon/pull/5151
=> propagate controlplane JWT

.github/workflows/lint-test.yaml, charts/neon-proxy/Chart.yaml, charts/neon-proxy/README.md, charts/neon-proxy/templates/deployment.yaml, charts/neon-proxy/values.yaml
depends on https://github.com/neondatabase/neon/pull/5799
=> proxy: add wake-compute-lock cli flag

charts/neon-storage-broker/Chart.yaml, charts/neon-storage-broker/README.md, charts/neon-storage-broker/values.yaml
storage broker max limit is unknown and it can get OMKilled, so setting back to no limit.
=> Revert storage broker resource limit

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/scripts/register-storage-controller.py, charts/neon-storage-controller/templates/post-install-job.yaml, charts/neon-storage-controller/templates/secrets-registration.yaml, charts/neon-storage-controller/templates/secrets.yaml
The binary expects `PAGESERVER_JWT_TOKEN`
=> Fix environment variable name

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/templates/secrets-registration.yaml, charts/neon-storage-controller/templates/secrets.yaml, charts/neon-storage-controller/values.yaml
also, separate token for registration and service itself
=> re-add control-plane token in secrets

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/templates/deployment.yaml, charts/neon-storage-controller/values.yaml
This enables switching on the functionality added in:
- https://github.com/neondatabase/neon/pull/7681
=> neon-storage-controller: add support for splitThreshold setting

charts/neon-proxy/Chart.yaml, charts/neon-proxy/README.md, charts/neon-proxy/templates/deployment.yaml
https://github.com/neondatabase/aws/pull/1396#issuecomment-2139384340
=> Proxy Add quotes

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/scripts/register-storage-controller.py, charts/neon-storage-controller/templates/post-install-job.yaml, charts/neon-storage-controller/values.yaml
We don't need to register storage-controllers in console anymore.
=> storage-controller: register only in control plane

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/templates/deployment.yaml, charts/neon-storage-controller/values.yaml
Maps to --chaos-interval flag.
=> neon-storage-controller: add chaosInterval setting

charts/neon-proxy/Chart.yaml, charts/neon-proxy/README.md, charts/neon-proxy/templates/deployment.yaml, charts/neon-proxy/templates/secrets.yaml
Fixes: neondatabase/cloud#16400
=> proxy: Pass controlplane token as secret

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/templates/secrets.yaml, charts/neon-storage-controller/values.yaml
See https://github.com/neondatabase/neon/pull/8764 and https://github.com/neondatabase/infra/pull/1750
=> Add peer jwt token value to storcon helm chart

charts/neon-storage-scrubber/Chart.yaml, charts/neon-storage-scrubber/README.md, charts/neon-storage-scrubber/templates/cronjob.yaml, charts/neon-storage-scrubber/values.yaml
Set a 1-day timeout for each job run, if it exceeds the timeout, the job should be killed and restarted.
=> feat(scrubber): add timeout for the cronjob

charts/neon-proxy/Chart.yaml, charts/neon-proxy/README.md, charts/neon-proxy/templates/deployment.yaml, charts/neon-proxy/values.yaml
was removed from proxy as it didn't do anything.
=> remove dynamic rate limit arg

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/scripts/register-storage-controller.py, charts/neon-storage-controller/templates/secrets-registration.yaml
Nothing seems to be checking this version so we just can hard-code it instead of looking up the most
recent Pageserver version in the region.
=> hard-code storage controller version

charts/neon-storage-broker/Chart.yaml, charts/neon-storage-broker/README.md, charts/neon-storage-broker/templates/deployment.yaml, charts/neon-storage-broker/values.yaml, charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/templates/deployment.yaml, charts/neon-storage-controller/values.yaml
Touches https://github.com/neondatabase/cloud/issues/26572.
=> neon-storage-{broker,controller}: add `priorityClassName`

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/templates/deployment.yaml
https://github.com/neondatabase/neon/pull/11703 introduced a new liveness endpoint
that takes into account leadership state. Switch to using that.
=> Use the new storcon liveness endpoint

charts/neon-pg-sni-router/Chart.yaml, charts/neon-pg-sni-router/README.md, charts/neon-pg-sni-router/templates/deployment.yaml, charts/neon-pg-sni-router/templates/root_ca.yaml, charts/neon-pg-sni-router/templates/service.exposed.yaml, charts/neon-pg-sni-router/values.yaml
Same as #134 but for pg-sni-router
See https://github.com/neondatabase/neon/pull/11732
=> pg-sni-router compute-tls

charts/neon-proxy/Chart.yaml, charts/neon-proxy/README.md, charts/neon-proxy/templates/certificate-pg-sni-router.yaml, charts/neon-proxy/templates/deployment.yaml, charts/neon-proxy/templates/service-pg-sni-router.exposed.yaml, charts/neon-proxy/values.yaml
See https://github.com/neondatabase/neon/pull/11882
=> add pg-sni-router to proxy

charts/neon-endpoint-storage/Chart.yaml, charts/neon-endpoint-storage/values.yaml
https://github.com/neondatabase/cloud/issues/27195
=> endpoint storage: explicit type in deployment

charts/neon-endpoint-storage/Chart.yaml, charts/neon-endpoint-storage/templates/extra-manifests.yaml
https://github.com/neondatabase/cloud/issues/19011
=> endpoint storage: add pod scrape

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/templates/deployment.yaml, charts/neon-storage-controller/values.yaml
part of https://github.com/neondatabase/neon/issues/11670
=> storcon: new timelinesOntoSafekeepers setting

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/templates/pod-disruption-budget.yaml
It's a best practice.
Refs:
- https://databricks.atlassian.net/browse/LKB-2547
=> storcon: add PodDisruptionBudget

charts/neon-storage-controller/Chart.yaml, charts/neon-storage-controller/README.md, charts/neon-storage-controller/templates/deployment.yaml, charts/neon-storage-controller/values.yaml
See https://github.com/databricks-eng/hadron/pull/1555
and https://databricks.atlassian.net/browse/LKB-2616
=> storcon: add --chaos-safekeeper-interval setting
